image: python:3.8

stages:
  - deploy

before_script: 
  - pip install -r requirements.txt

pages:
  stage: deploy
  script:
    - make doc
  artifacts:
      paths:
      - public
  only:
    - master
